[FIX] website_penguin_odoo:
ImportError: cannot import name 'controllers' from partially initialized module 'odoo.addons.website_penguin_odoo' (most likely due to a circular import) (/home/odoo/src/user/extra-addons/website_penguin_odoo/__init__.py)